# See https://www.apollographql.com/docs/federation/quickstart/#configuration-file
# for more info
federation_version: 2
subgraphs:
# Uncomment/Add your subgraphs here to run locally
  # featureflags: 
  #   routing_url: https://featureflags.readitlater.com/graphql
  #   schema:
  #     subgraph_url: https://featureflags.readitlater.com/graphql
  # user: 
  #   routing_url: https://user-api.readitlater.com
  #   schema:
  #     subgraph_url: https://user-api.readitlater.com
  # parser:
  #   routing_url: http://localhost:4001
  #   schema:
  #     subgraph_url: http://localhost:4001
  # user-api:
  #   routing_url: http://localhost:4006
  #   schema:
  #     subgraph_url: http://localhost:4006
  