const nonUserTables = [
  { table: 'readitla_ril-tmp.bundle_users', where: 'email' },
  { table: 'readitla_ril-tmp.log_login_data', where: 'email' },
  {
    table: 'readitla_ril-tmp.paypal_transaction_log',
    where: 'payer_email',
  },
  {
    table: 'readitla_ril-tmp.paypal_transaction_error_log',
    where: 'payer_email',
  },
  {
    table: 'readitla_ril-tmp.publisher_users_invites',
    where: 'invited_email',
  },
];

//excludes any table that is handled by list-api,
//annotations-api, and user-api
//delete by `user_id`
const tablesWithUserId: {
  tablesWithSensitivePii: string[];
  tablesWithUserIdAlone: string[];
} = {
  //tables with column patterns: name, username, first_name, last_name,
  // email, ip and device_name
  tablesWithSensitivePii: [
    'readitla_ril-tmp.list',
    'readitla_ril-tmp.item_tags',
    'readitla_ril-tmp.item_attribution',
    'readitla_auth.user_providers',
    'readitla_ril-tmp.api_users',
    'readitla_ril-tmp.email_interest',
    'readitla_ril-tmp.friends',
    'readitla_ril-tmp.mozilla_users_to_upgrade',
    'readitla_ril-tmp.newsletter_subscribers',
    'readitla_ril-tmp.users_ac_emails',
    'readitla_ril-tmp.digest_users',
    'readitla_ril-tmp.user_aol_account',
    'readitla_ril-tmp.user_upday_account',
    'readitla_ril-tmp.user_ip',
    'readitla_ril-tmp.user_shared_lists',
    'readitla_ril-tmp.user_stripe',
    'readitla_ril-tmp.user_subscription',
    'readitla_ril-tmp.user_subscription_history',
    'readitla_ril-tmp.user_wildtangent_info',
    'readitla_ril-tmp.login_meta',
    'readitla_ril-tmp.social_profile',
    'readitla_ril-tmp.projectx_twitter_accounts',
    'readitla_ril-tmp.projectx_users',
    'readitla_ril-tmp.publisher_users',
    //contains names of other users,
    // or related to a company or a device
    'readitla_ril-tmp.user_track',
    'readitla_ril-tmp.user_action_dupes',
    'readitla_ril-tmp.spoc_campaigns',
    'readitla_ril-tmp.shares_recipients',
    'readitla_ril-tmp.user_message_action',
    'readitla_ril-tmp.campaign_target',
  ],
  tablesWithUserIdAlone: [
    'readitla_analytics.FACT_publisher_data',
    'readitla_analytics.ROLLUP_annual_publisher_data',
    'readitla_analytics.ROLLUP_monthly_publisher_data',
    'readitla_analytics.ROLLUP_quarterly_publisher_data',
    'readitla_b.article_reports',
    'readitla_b.c2dm_pending_pings',
    'readitla_b.parser_rules',
    'readitla_b.parser_rules_staging',
    'readitla_b.stats_errors',
    'readitla_b.stats_guids',
    'readitla_b.user_grouping_item',
    'readitla_b.user_grouping_item_raw',
    'readitla_b.user_grouping_score',
    'readitla_b.user_grouping_stats',
    'readitla_b.user_item_backfill_tracking',
    'readitla_b.user_item_score',
    'readitla_b.user_item_stats_test',
    'readitla_ril-tmp.item_session',
    'readitla_ril-tmp.ab_test_user_accounts',
    'readitla_ril-tmp.acl_rules',
    'readitla_ril-tmp.ad_api_track',
    'readitla_ril-tmp.ad_report',
    'readitla_ril-tmp.admin_acl',
    'readitla_ril-tmp.admin_roles_users',
    'readitla_ril-tmp.admin_users',
    'readitla_ril-tmp.advertiser',
    'readitla_ril-tmp.android_transaction_log',
    'readitla_ril-tmp.api_app_users',
    'readitla_ril-tmp.app_segment',
    'readitla_ril-tmp.app_session',
    'readitla_ril-tmp.comments',
    'readitla_ril-tmp.contact_hashes',
    'readitla_ril-tmp.contact_index',
    'readitla_ril-tmp.contact_sort',
    'readitla_ril-tmp.digest_batch',
    'readitla_ril-tmp.digest_list',
    'readitla_ril-tmp.digest_topics_users',
    'readitla_ril-tmp.digest_users_locks',
    'readitla_ril-tmp.email_digest_history',
    'readitla_ril-tmp.eoy_2014_user_devices',
    'readitla_ril-tmp.eoy_2014_user_items',
    'readitla_ril-tmp.eoy_2014_user_summary',
    'readitla_ril-tmp.eoy_2014_user_topics',
    'readitla_ril-tmp.eoy_2014_user_weekdays',
    'readitla_ril-tmp.eoy_2015_topic_suggestions',
    'readitla_ril-tmp.eoy_2015_user_items',
    'readitla_ril-tmp.eoy_2015_user_summary',
    'readitla_ril-tmp.eoy_2015_user_topics',
    'readitla_ril-tmp.eoy_2016_user_items',
    'readitla_ril-tmp.eoy_2016_user_summary',
    'readitla_ril-tmp.eoy_2016_user_topics',
    'readitla_ril-tmp.eoy_2017_user_items',
    'readitla_ril-tmp.eoy_2017_user_summary',
    'readitla_ril-tmp.eoy_2017_user_topics',
    'readitla_ril-tmp.eoy_2018_user_items',
    'readitla_ril-tmp.eoy_2018_user_summary',
    'readitla_ril-tmp.eoy_2018_user_topics',
    'readitla_ril-tmp.eoy_2019_user_items',
    'readitla_ril-tmp.eoy_2019_user_summary',
    'readitla_ril-tmp.eoy_2019_user_topics',
    'readitla_ril-tmp.feed_item_reports',
    'readitla_ril-tmp.feed_user_recommendations',
    'readitla_ril-tmp.friend_joined_notification_log',
    'readitla_ril-tmp.galapagos_alpha_testers',
    'readitla_ril-tmp.galaxy_gifts_track',
    'readitla_ril-tmp.ios_transaction_error_log',
    'readitla_ril-tmp.ios_transaction_log',
    //removed item_groupings due to large table size
    //the select query causes db overload
    //'readitla_ril-tmp.item_groupings',
    'readitla_ril-tmp.likes',
    'readitla_ril-tmp.log_overflow_action_data',
    'readitla_ril-tmp.messages',
    'readitla_ril-tmp.post_actions',
    'readitla_ril-tmp.projectx_feed_items',
    'readitla_ril-tmp.projectx_feed_items_viewed',
    'readitla_ril-tmp.projectx_friends',
    'readitla_ril-tmp.campaign_target',
    'readitla_ril-tmp.projectx_posted_items',
    'readitla_ril-tmp.projectx_friends_tags',
    'readitla_ril-tmp.projectx_notifications',
    'readitla_ril-tmp.projectx_post_comments',
    'readitla_ril-tmp.projectx_post_likes',
    'readitla_ril-tmp.projectx_post_reposts',
    'readitla_ril-tmp.projectx_posted_items',
    'readitla_ril-tmp.projectx_posted_items_to_update',
    'readitla_ril-tmp.projectx_subscriptions',
    'readitla_ril-tmp.projectx_user_feed',
    'readitla_ril-tmp.promotion_codes',
    'readitla_ril-tmp.push_tokens',
    'readitla_ril-tmp.share_unviewed',
    'readitla_ril-tmp.share_urls',
    'readitla_ril-tmp.share_urls_log',
    'readitla_ril-tmp.shared_items',
    'readitla_ril-tmp.shares',
    'readitla_ril-tmp.shares_friends',
    'readitla_ril-tmp.track_app_links_log',
    'readitla_ril-tmp.track_errors',
    'readitla_ril-tmp.track_log',
    'readitla_ril-tmp.track_values_log',
    'readitla_ril-tmp.user_action_ifttt',
    'readitla_ril-tmp.user_ctas',
    'readitla_ril-tmp.user_friends',
    'readitla_ril-tmp.user_ghost_account',
    'readitla_ril-tmp.user_google_lookup',
    'readitla_ril-tmp.user_highlights_process_schedule',
    'readitla_ril-tmp.user_item_backfill_queue',
    'readitla_ril-tmp.user_library_backfill_status',
    'readitla_ril-tmp.user_list_size',
    'readitla_ril-tmp.user_locale',
    'readitla_ril-tmp.user_precache',
    'readitla_ril-tmp.user_premium_cleanup',
    'readitla_ril-tmp.user_premium_status',
    'readitla_ril-tmp.user_promotion',
    'readitla_ril-tmp.user_promotion_track',
    'readitla_ril-tmp.user_recent_friends',
    'readitla_ril-tmp.user_recent_search',
    'readitla_ril-tmp.user_rediscovery_status',
    'readitla_ril-tmp.user_search_backfill_status',
    'readitla_ril-tmp.user_web_session_tokens',
    'readitla_ril-tmp.users_admin',
    'readitla_ril-tmp.users_blocked',
    'readitla_ril-tmp.users_bronto',
    'readitla_ril-tmp.users_collections_following',
    'readitla_ril-tmp.users_friends',
    'readitla_ril-tmp.users_friends_following',
    'readitla_ril-tmp.view_segment',
    'readitla_ril-tmp.list_meta',
    'readitla_ril-tmp.items_scroll',
    'readitla_ril-tmp.item_ads',
    'readitla_ril-tmp.item_time_spent',
    'readitla_ril-tmp.item_currently_reading',
    'readitla_ril-tmp.list_extras',
    'readitla_ril-tmp.list_shares',
  ],
};

const userTables: string[] = [
  ...tablesWithUserId.tablesWithSensitivePii,
  ...tablesWithUserId.tablesWithUserIdAlone,
];

export const tables = [
  ...nonUserTables,
  ...userTables.map((name) => ({ table: name, where: 'user_id' })),
];

/**
Query to fetch these tables:
 https://getpocket.atlassian.net/wiki/spaces/CP/pages/2694152202/Backend+Data+Deletion+-+Data+Retention+and+Deletion#Tables-with-user_id-(or)-email,-and-has-no-primary-key-but-an-index
 Note: excluded any tables in `readitla_analytics`, and those
 tables handled by user-api, list-api and annotations-api
 all these tables have only `user_id` as a the `where` condition
 */
export const indexedTables = {
  'readitla_b.article_reports': ['item_id'],
  'readitla_b.stats_errors': ['api_id'],
  'readitla_ril-tmp.login_failures': ['ip_address'],
  'readitla_ril-tmp.shares': ['item_id'],
  'readitla_ril-tmp.projectx_feed_items_viewed': ['time_updated'],
  'readitla_ril-tmp.track_app_links_log': ['source', 'camp_id', 'version'],
  'readitla_ril-tmp.track_errors': ['api_id', 'time_happened'],
  'readitla_ril-tmp.track_log': ['camp_id'],
};
