name: 'Checkout & Install pnpm and node'
description: 'Install dependencies using pnpm'
inputs:
  scope:
    description: 'Package scope to use from turbo repo'
    default: ''  # Empty string as default value
    required: false

runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        # Don't specify a pnpm version, to use the one defined in the top level package.json
        run_install: false
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        # Use .nvmrc to determine our Node Version
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        if [ -z "${{ inputs.scope }}" ]; then
          echo "No scope provided. Using default behavior."
          pnpm install --frozen-lockfile
        else
          echo "Scope provided: ${{ inputs.scope }}, only installing packages needed for it."
          pnpm install --filter=${{inputs.scope}}... --frozen-lockfile
        fi