export enum Event {
  ADD_ITEM = 'ADD_ITEM',
  DELETE_ITEM = 'DELETE_ITEM',
  FAVORITE_ITEM = 'FAVORITE_ITEM',
  UNFAVORITE_ITEM = 'UNFAVORITE_ITEM',
  ARCHIVE_ITEM = 'ARCHIVE_ITEM',
  UNARCHIVE_ITEM = 'UNARCHIVE_ITEM',
  ADD_TAGS = 'ADD_TAGS',
  REPLACE_TAGS = 'REPLACE_TAGS',
  CLEAR_TAGS = 'CLEAR_TAGS',
  REMOVE_TAGS = 'REMOVE_TAGS',
  RENAME_TAG = 'RENAME_TAG',
  DELETE_TAG = 'DELETE_TAG',
}
