/* eslint-disable */
/***
 * PasswordResetInfo schema class generated by the schema registry code bindings
 */
export class PasswordResetInfo {
  'resetPasswordToken': string;
  'resetPasswordUsername': string;
  'timestamp': number;

  private static discriminator: string | undefined = undefined;

  private static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'resetPasswordToken',
      baseName: 'resetPasswordToken',
      type: 'string',
    },
    {
      name: 'resetPasswordUsername',
      baseName: 'resetPasswordUsername',
      type: 'string',
    },
    {
      name: 'timestamp',
      baseName: 'timestamp',
      type: 'number',
    },
  ];

  public static getAttributeTypeMap() {
    return PasswordResetInfo.attributeTypeMap;
  }
}
