
workflows:
  account-data-deleter:
    jobs:

      - test_integrations:
          <<: *not_dev_main
          for: account_data_deleter
          context: pocket
          name: account-data-deleter_test_integrations
          scope: account-data-deleter

      - test_integrations:
          <<: *not_dev_main
          for: account_data_deleter
          context: pocket
          name: account-data-deleter_batch-delete_test_integrations
          scope: account-data-deleter-batch-delete


      # Try building the ECS docker image on each branch
      - build_image:
          <<: *not_dev_main
          context: pocket
          for: account_data_deleter
          name: account_data_deleter_build_docker
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: accountdatadeleter-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: false
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=account-data-deleter --build-arg APP_PATH=servers/account-data-deleter --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=account-data-deleter --build-arg PORT=4015
     
      ######
      # Every PR Jobs
      ######
      - build_lambda:
          <<: *not_dev_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_build_events
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: account-data-deleter-events
          sentry_project_name: account-data-deleter
          sentry_env: development
          sentry_org: pocket

      - build_lambda:
          <<: *not_dev_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_build_batch-delete
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: account-data-deleter-batch-delete
          sentry_project_name: account-data-deleter
          sentry_env: development
          sentry_org: pocket

      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_infrastructure_plan_prod
          scope: account-data-deleter-cdk
          stack-output-path: infrastructure/account-data-deleter/cdktf.out/stacks/account-data-deleter
          resource-class: pocket/default-prod
          workspace: Prod
          dev: false
          apply: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_infrastructure_apply_dev
          scope: account-data-deleter-cdk
          stack-output-path: infrastructure/account-data-deleter/cdktf.out/stacks/account-data-deleter
          resource-class: pocket/default-dev
          workspace: Dev
          apply: true
          dev: true

      # Build & Deploy the Dev Docker Image
      - build_image:
          <<: *only_dev
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_build_docker_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: accountdatadeleter-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=account-data-deleter --build-arg APP_PATH=servers/account-data-deleter --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=account-data-deleter --build-arg PORT=4015
          requires:
            - account-data-deleter_infrastructure_apply_dev

      - code_deploy_ecs:
          <<: *only_dev
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_code_deploy_ecs_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: AccountDataDeleter-Dev-ECS
          codedeploy-group-name: AccountDataDeleter-Dev-ECS
          requires:
            - account-data-deleter_build_docker_dev

      - build_lambda:
          <<: *only_dev
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_events_build_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: account-data-deleter-events
          sentry_project_name: account-data-deleter
          sentry_env: development
          sentry_org: pocket
          s3-bucket: 	pocket-accountdatadeleter-dev-sqs-event-consumer
          requires:
            - account-data-deleter_infrastructure_apply_dev

      - code_deploy_lambda:
          <<: *only_dev
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_events_code_deploy_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: AccountDataDeleter-Dev-Sqs-Event-Consumer-Lambda
          codedeploy-group-name: AccountDataDeleter-Dev-Sqs-Event-Consumer-Lambda
          function-name: AccountDataDeleter-Dev-Sqs-Event-Consumer-Function
          s3-bucket: 	pocket-accountdatadeleter-dev-sqs-event-consumer
          requires:
            - account-data-deleter_events_build_dev

      - build_lambda:
          <<: *only_dev
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_batch-delete_build_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: account-data-deleter-batch-delete
          sentry_project_name: account-data-deleter
          sentry_env: development
          sentry_org: pocket
          s3-bucket: 	pocket-accountdatadeleter-dev-batchdeletelambda
          requires:
            - account-data-deleter_infrastructure_apply_dev

      - code_deploy_lambda:
          <<: *only_dev
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_batch-delete_code_deploy_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: AccountDataDeleter-Dev-BatchDeleteLambda-Lambda
          codedeploy-group-name: AccountDataDeleter-Dev-BatchDeleteLambda-Lambda
          function-name: AccountDataDeleter-Dev-BatchDeleteLambda-Function
          s3-bucket: 	pocket-accountdatadeleter-dev-batchdeletelambda
          requires:
            - account-data-deleter_batch-delete_build_dev


      # Notify sentry of dev deployment
      - sentry_release_notification:
          <<: *only_dev
          name: account-data-deleter_sentry-release-notification-dev
          context: pocket
          for: account_data_deleter
          sentry_project_name: account-data-deleter
          sentry_env: development
          sentry_org: pocket
          requires:
            - account-data-deleter_events_code_deploy_dev
            - account-data-deleter_batch-delete_code_deploy_dev
            - account-data-deleter_code_deploy_ecs_dev

      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_dev
          name: account-data-deleter_deploy-params-dev
          aws_access_key_id: Dev_AWS_ACCESS_KEY
          aws_secret_access_key: Dev_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Dev
          service_name: AccountDataDeleter
          requires:
            - account-data-deleter_events_code_deploy_dev
            - account-data-deleter_batch-delete_code_deploy_dev
            - account-data-deleter_code_deploy_ecs_dev

      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_infrastructure_apply_prod
          scope: account-data-deleter-cdk
          stack-output-path: infrastructure/account-data-deleter/cdktf.out/stacks/account-data-deleter
          resource-class: pocket/default-prod
          workspace: Prod
          apply: true
          dev: false

      # Build & Deploy the Prod Docker Image
      - build_image:
          <<: *only_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_build_docker_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          repo-name: accountdatadeleter-prod-app
          ecr-url: 996905175585.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=account-data-deleter --build-arg APP_PATH=servers/account-data-deleter --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=account-data-deleter --build-arg PORT=4015
          requires:
            - account-data-deleter_infrastructure_apply_prod

      - code_deploy_ecs:
          <<: *only_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_code_deploy_ecs_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: AccountDataDeleter-Prod-ECS
          codedeploy-group-name: AccountDataDeleter-Prod-ECS
          requires:
            - account-data-deleter_build_docker_prod

      - build_lambda:
          <<: *only_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_events_build_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          scope: account-data-deleter-events
          sentry_project_name: account-data-deleter
          sentry_env: development
          sentry_org: pocket
          s3-bucket: 	pocket-accountdatadeleter-prod-sqs-event-consumer
          requires:
            - account-data-deleter_infrastructure_apply_prod

      - code_deploy_lambda:
          <<: *only_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_events_code_deploy_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: AccountDataDeleter-Prod-Sqs-Event-Consumer-Lambda
          codedeploy-group-name: AccountDataDeleter-Prod-Sqs-Event-Consumer-Lambda
          function-name: AccountDataDeleter-Prod-Sqs-Event-Consumer-Function
          s3-bucket: 	pocket-accountdatadeleter-prod-sqs-event-consumer
          requires:
            - account-data-deleter_events_build_prod

      - build_lambda:
          <<: *only_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_batch-delete_build_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          scope: account-data-deleter-batch-delete
          sentry_project_name: account-data-deleter
          sentry_env: prodelopment
          sentry_org: pocket
          s3-bucket: 	pocket-accountdatadeleter-prod-batchdeletelambda
          requires:
            - account-data-deleter_infrastructure_apply_prod

      - code_deploy_lambda:
          <<: *only_main
          context: pocket
          for: account_data_deleter
          name: account-data-deleter_batch-delete_code_deploy_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: AccountDataDeleter-Prod-BatchDeleteLambda-Lambda
          codedeploy-group-name: AccountDataDeleter-Prod-BatchDeleteLambda-Lambda
          function-name: AccountDataDeleter-Prod-BatchDeleteLambda-Function
          s3-bucket: 	pocket-accountdatadeleter-prod-batchdeletelambda
          requires:
            - account-data-deleter_batch-delete_build_prod


      # Notify sentry of prod deployment
      - sentry_release_notification:
          <<: *only_main
          name: account-data-deleter_sentry-release-notification-prod
          context: pocket
          for: account_data_deleter
          sentry_project_name: account-data-deleter
          sentry_env: prodelopment
          sentry_org: pocket
          requires:
            - account-data-deleter_events_code_deploy_prod
            - account-data-deleter_batch-delete_code_deploy_prod
            - account-data-deleter_code_deploy_ecs_prod

      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_main
          name: account-data-deleter_deploy-params-prod
          aws_access_key_id: Prod_AWS_ACCESS_KEY
          aws_secret_access_key: Prod_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Prod
          service_name: AccountDataDeleter
          requires:
            - account-data-deleter_events_code_deploy_prod
            - account-data-deleter_batch-delete_code_deploy_prod
            - account-data-deleter_code_deploy_ecs_prod

