
workflows:
  account-delete-monitor:
    jobs:

      ######
      # Every PR Jobs
      ######
      - build_lambda:
          <<: *not_dev_main
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_build_lambda
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: account-delete-monitor
          sentry_project_name: account-delete-monitor
          sentry_env: development
          sentry_org: pocket

      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_infrastructure_plan_prod
          scope: account-delete-monitor-cdk
          stack-output-path: infrastructure/account-delete-monitor/cdktf.out/stacks/account-delete-monitor
          resource-class: pocket/default-prod
          workspace: Prod
          dev: false
          apply: false
          save_app_spec: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_infrastructure_apply_dev
          scope: account-delete-monitor-cdk
          stack-output-path: infrastructure/account-delete-monitor/cdktf.out/stacks/account-delete-monitor
          resource-class: pocket/default-dev
          workspace: Dev
          apply: true
          dev: true
          save_app_spec: false

      - build_lambda:
          <<: *only_dev
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_events_build_lambda_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: account-delete-monitor
          sentry_project_name: account-delete-monitor
          sentry_env: development
          sentry_org: pocket
          s3-bucket: pocket-accountdeletemonitor-dev-sqs-event-consumer
          requires:
            - account-delete-monitor_infrastructure_apply_dev

      - code_deploy_lambda:
          <<: *only_dev
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_events_code_deploy_lambda_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: AccountDeleteMonitor-Dev-Sqs-Event-Consumer-Lambda
          codedeploy-group-name: AccountDeleteMonitor-Dev-Sqs-Event-Consumer-Lambda
          function-name: AccountDeleteMonitor-Dev-Sqs-Event-Consumer-Function
          s3-bucket: pocket-accountdeletemonitor-dev-sqs-event-consumer
          requires:
            - account-delete-monitor_events_build_lambda_dev

      # Notify sentry of dev deployment
      - sentry_release_notification:
          <<: *only_dev
          name: account-delete-monitor_sentry-release-notification-dev
          context: pocket
          for: account_delete_monitor
          sentry_project_name: account-delete-monitor
          sentry_env: development
          sentry_org: pocket
          requires:
            - account-delete-monitor_events_code_deploy_lambda_dev

      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_dev
          name: account-delete-monitor_deploy-params-dev
          aws_access_key_id: Dev_AWS_ACCESS_KEY
          aws_secret_access_key: Dev_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Dev
          service_name: AccountDeleteMonitor
          requires:
            - account-delete-monitor_events_code_deploy_lambda_dev

      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_infrastructure_apply_prod
          scope: account-delete-monitor-cdk
          stack-output-path: infrastructure/account-delete-monitor/cdktf.out/stacks/account-delete-monitor
          resource-class: pocket/default-prod
          workspace: Prod
          apply: true
          dev: false
          save_app_spec: false

      - build_lambda:
          <<: *only_main
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_events_build_lambda_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          scope: account-delete-monitor
          sentry_project_name: account-delete-monitor
          sentry_env: production
          sentry_org: pocket
          s3-bucket: pocket-accountdeletemonitor-prod-sqs-event-consumer
          requires:
            - account-delete-monitor_infrastructure_apply_prod

      - code_deploy_lambda:
          <<: *only_main
          context: pocket
          for: account_delete_monitor
          name: account-delete-monitor_events_code_deploy_lambda_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: AccountDeleteMonitor-Prod-Sqs-Event-Consumer-Lambda
          codedeploy-group-name: AccountDeleteMonitor-Prod-Sqs-Event-Consumer-Lambda
          function-name: AccountDeleteMonitor-Prod-Sqs-Event-Consumer-Function
          s3-bucket: pocket-accountdeletemonitor-prod-sqs-event-consumer
          requires:
            - account-delete-monitor_events_build_lambda_prod

      # Notify sentry of main deployment
      - sentry_release_notification:
          <<: *only_main
          name: account-delete-monitor_sentry-release-notification-prod
          context: pocket
          for: account_delete_monitor
          sentry_project_name: account-delete-monitor
          sentry_env: production
          sentry_org: pocket
          requires:
            - account-delete-monitor_events_code_deploy_lambda_prod

      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_main
          name: account-delete-monitor_deploy-params-prod
          aws_access_key_id: Prod_AWS_ACCESS_KEY
          aws_secret_access_key: Prod_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Prod
          service_name: AccountDeleteMonitor
          requires:
            - account-delete-monitor_events_code_deploy_lambda_prod
