
workflows:
  braze:
    jobs:

      ######
      # Every PR Jobs
      ######

      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: braze
          name: braze_infrastructure_plan_prod
          scope: braze-cdk
          stack-output-path: infrastructure/braze/cdktf.out/stacks/braze
          resource-class: pocket/default-prod
          dev: false
          apply: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: braze
          name: braze_infrastructure_apply_dev
          scope: braze-cdk
          stack-output-path: infrastructure/braze/cdktf.out/stacks/braze
          resource-class: pocket/default-dev
          apply: true
          dev: true


      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: braze
          name: braze_infrastructure_apply_prod
          scope: braze-cdk
          stack-output-path: infrastructure/braze/cdktf.out/stacks/braze
          resource-class: pocket/default-prod
          apply: true
          dev: false
