
workflows:
  client-api:
    jobs:
      # Try building the ECS docker image on each branch
      - build_image:
          <<: *not_dev_main
          context: pocket
          for: client_api
          name: client-api_build_docker
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: clientapi-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: false
          app_path: 'servers/client-api'
          layer_caching: false
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1}
     
      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: client_api
          name: client-api_infrastructure_plan_prod
          scope: client-api-cdk
          stack-output-path: infrastructure/client-api/cdktf.out/stacks/client-api
          resource-class: pocket/default-prod
          dev: false
          apply: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: client_api
          name: client-api_infrastructure_apply_dev
          scope: client-api-cdk
          stack-output-path: infrastructure/client-api/cdktf.out/stacks/client-api
          resource-class: pocket/default-dev
          apply: true
          dev: true

      # Build & Deploy the Dev Docker Image
      - build_image:
          <<: *only_dev
          context: pocket
          for: client_api
          name: client-api_build_docker_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: clientapi-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: true
          app_path: 'servers/client-api'
          layer_caching: false
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1}
          requires:
            - client-api_infrastructure_apply_dev

      - code_deploy_ecs:
          <<: *only_dev
          context: pocket
          for: client_api
          name: client-api_code_deploy_ecs_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: ClientAPI-Dev-ECS
          codedeploy-group-name: ClientAPI-Dev-ECS
          requires:
            - client-api_build_docker_dev

      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: client_api
          name: client-api_infrastructure_apply_prod
          scope: client-api-cdk
          stack-output-path: infrastructure/client-api/cdktf.out/stacks/client-api
          resource-class: pocket/default-prod
          apply: true
          dev: false

      # Build & Deploy the Prod Docker Image
      - build_image:
          <<: *only_main
          context: pocket
          for: client_api
          name: client-api_build_docker_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          repo-name: clientapi-prod-app
          ecr-url: 996905175585.dkr.ecr.us-east-1.amazonaws.com
          push: true
          app_path: 'servers/client-api'
          layer_caching: false
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1}
          requires:
            - client-api_infrastructure_apply_prod

      - code_deploy_ecs:
          <<: *only_main
          context: pocket
          for: client_api
          name: client-api_code_deploy_ecs_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: ClientAPI-Prod-ECS
          codedeploy-group-name: ClientAPI-Prod-ECS
          requires:
            - client-api_build_docker_prod
