workflows:
  corpus-search:
    jobs:

      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: corpus_search
          name: corpus-search_infrastructure_plan_prod
          stack-output-path: infrastructure/corpus-search
          scope: corpus-search-cdk
          resource-class: pocket/default-prod
          dev: false
          apply: false
          uses_raw_hcl: true

      # ######
      # # Dev Branch Deployment (Dev Environment)
      # ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: user_list_search
          name: corpus-search_infrastructure_apply_dev
          stack-output-path: infrastructure/corpus-search
          scope: corpus-search-cdk
          resource-class: pocket/default-dev
          apply: true
          dev: true
          uses_raw_hcl: true


      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: user_list_search
          name: corpus-search_infrastructure_apply_prod
          scope: corpus-search-cdk
          stack-output-path: infrastructure/corpus-search
          resource-class: pocket/default-prod
          apply: true
          dev: false
          uses_raw_hcl: true
