workflows:
  corpus-embeddings:
    jobs:


      ######
      # Every PR Jobs
      ######
      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: corpus_embeddings
          name: corpus-embeddings_infrastructure_plan_prod
          stack-output-path: infrastructure/corpus-embeddings
          scope: corpus-embeddings-cdk
          resource-class: pocket/default-prod
          dev: false
          apply: false
          uses_raw_hcl: true
      
      - build_lambda:
          <<: *not_dev_main
          context: pocket
          for: corpus_embeddings
          name: corpus-embeddings-connector_build_lambda
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: corpus-embeddings-connector-creator
          sentry_project_name: corpus-embeddings
          sentry_env: development
          sentry_org: pocket

      # ######
      # # Dev Branch Deployment (Dev Environment)
      # ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: corpus_embeddings
          name: corpus-embeddings_infrastructure_apply_dev
          stack-output-path: infrastructure/corpus-embeddings
          scope: corpus-embeddings-cdk
          resource-class: pocket/default-dev
          apply: true
          dev: true
          uses_raw_hcl: true
      
      - build_lambda:
          <<: *only_dev
          context: pocket
          for: corpus_embeddings
          name: corpus-embeddings-connector_build_lambda_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: corpus-embeddings-connector-creator
          sentry_project_name: corpus-embeddings
          sentry_env: development
          sentry_org: pocket
          s3-bucket: pocket-corpusembeddings-dev-lambdas
          s3-key: corpus-embeddings-connector-creator-$CIRCLE_SHA1.zip
          requires:
            - corpus-embeddings_infrastructure_apply_dev
        
      - code_deploy_lambda:
          <<: *only_dev
          context: pocket
          for: corpus_embeddings
          name: corpus-embeddings-connector_code_deploy_lambda_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: CorpusEmbeddings-Dev-CreateMlConnector
          codedeploy-group-name: CorpusEmbeddings-Dev-CreateMlConnector
          function-name: CorpusEmbeddings-Dev-CreateMlConnector
          s3-bucket: pocket-corpusembeddings-dev-lambdas
          s3-key: corpus-embeddings-connector-creator-$CIRCLE_SHA1.zip
          requires:
            - corpus-embeddings-connector_build_lambda_dev

      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: corpus_embeddings
          name: corpus-embeddings_infrastructure_apply_prod
          scope: corpus-embeddings-cdk
          stack-output-path: infrastructure/corpus-embeddings
          resource-class: pocket/default-prod
          apply: true
          dev: false
          uses_raw_hcl: true
      
      - build_lambda:
          <<: *only_main
          context: pocket
          for: corpus_embeddings
          name: corpus-embeddings-connector_build_lambda_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          scope: corpus-embeddings-connector-creator
          sentry_project_name: corpus-embeddings
          sentry_env: production
          sentry_org: pocket
          s3-bucket: pocket-corpusembeddings-prod-lambdas
          s3-key: corpus-embeddings-connector-creator-$CIRCLE_SHA1.zip
          requires:
            - corpus-embeddings_infrastructure_apply_prod
        
      - code_deploy_lambda:
          <<: *only_main
          context: pocket
          for: user_list_search
          name:  corpus-embeddings-connector_code_deploy_lambda_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: CorpusEmbeddings-Prod-CreateMlConnector
          codedeploy-group-name: CorpusEmbeddings-Prod-CreateMlConnector
          function-name: CorpusEmbeddings-Prod-CreateMlConnector
          s3-bucket: pocket-corpusembeddings-prod-lambdas
          s3-key: corpus-embeddings-connector-creator-$CIRCLE_SHA1.zip
          requires:
            -  corpus-embeddings-connector_build_lambda_prod
