
workflows:
  feature-flags:
    jobs:

      ######
      # Every PR Jobs
      ######
      - apollo:
          name: feature-flags_apollo
          fed_graph_name: pocket-client-api
          graph_name: featureflags
          schema_file_path: servers/feature-flags/schema.graphql
          prod_graph_url: https://featureflags.readitlater.com/graphql
          dev_graph_url: https://featureflags.getpocket.dev/graphql

      # Try building the ECS docker image on each branch
      - build_image:
          <<: *not_dev_main
          context: pocket
          for: feature_flags
          name: feature-flags_build_docker
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: featureflags-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: false
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=feature-flags --build-arg APP_PATH=servers/feature-flags --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=feature-flags --build-arg PORT=4242 
     
      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: feature_flags
          name: feature-flags_infrastructure_plan_prod
          scope: feature-flags-cdk
          stack-output-path: infrastructure/feature-flags/cdktf.out/stacks/feature-flags
          resource-class: pocket/default-prod
          dev: false
          apply: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: feature_flags
          name: feature-flags_infrastructure_apply_dev
          scope: feature-flags-cdk
          stack-output-path: infrastructure/feature-flags/cdktf.out/stacks/feature-flags
          resource-class: pocket/default-dev
          apply: true
          dev: true

      # Build & Deploy the Dev Docker Image
      - build_image:
          <<: *only_dev
          context: pocket
          for: feature_flags
          name: feature-flags_build_docker_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: featureflags-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=feature-flags --build-arg APP_PATH=servers/feature-flags --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=feature-flags --build-arg PORT=4242
          requires:
            - feature-flags_infrastructure_apply_dev

      - code_deploy_ecs:
          <<: *only_dev
          context: pocket
          for: feature_flags
          name: feature-flags_code_deploy_ecs_dev
          resource-class: pocket/default-dev
          requires:
            - feature-flags_build_docker_dev

      # Notify sentry of dev deployment
      - sentry_release_notification:
          <<: *only_dev
          name: feature-flags_sentry-release-notification-dev
          context: pocket
          for: feature_flags
          sentry_project_name: feature-flags
          sentry_env: development
          sentry_org: pocket
          requires:
            - feature-flags_code_deploy_ecs_dev

      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: feature_flags
          name: feature-flags_infrastructure_apply_prod
          scope: feature-flags-cdk
          stack-output-path: infrastructure/feature-flags/cdktf.out/stacks/feature-flags
          resource-class: pocket/default-prod
          apply: true
          dev: false

      # Build & Deploy the Prod Docker Image
      - build_image:
          <<: *only_main
          context: pocket
          for: feature_flags
          name: feature-flags_build_docker_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          repo-name: featureflags-prod-app
          ecr-url: 996905175585.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=feature-flags --build-arg APP_PATH=servers/feature-flags --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=feature-flags --build-arg PORT=4242
          requires:
            - feature-flags_infrastructure_apply_prod

      - code_deploy_ecs:
          <<: *only_main
          context: pocket
          for: feature_flags
          name: feature-flags_code_deploy_ecs_prod
          resource-class: pocket/default-prod
          requires:
            - feature-flags_build_docker_prod

      # Notify sentry of main deployment
      - sentry_release_notification:
          <<: *only_main
          name: feature-flags_sentry-release-notification-prod
          context: pocket
          for: feature_flags
          sentry_project_name: feature-flags
          sentry_env: production
          sentry_org: pocket
          requires:
            - feature-flags_code_deploy_ecs_prod
