
workflows:
  list-api:
    jobs:

      ######
      # Every PR Jobs
      ######
      - apollo:
          name: list-api_apollo
          fed_graph_name: pocket-client-api
          graph_name: list
          schema_file_path: servers/list-api/dist/schema-generated.graphql
          prod_graph_url: https://list-api.readitlater.com
          dev_graph_url: https://list-api.getpocket.dev
          build_command: pnpm run build --filter=list-api...


      - test_integrations:
          <<: *not_dev_main
          for: list_api
          context: pocket
          name: list-api_test_integrations
          scope: list-api

      # Try building the ECS docker image on each branch
      - build_image:
          <<: *not_dev_main
          context: pocket
          for: list_api
          name: list-api_build_docker
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: listapi-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: false
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=list-api --build-arg APP_PATH=servers/list-api --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=list-api --build-arg PORT=4005 
     
      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: list_api
          name: list-api_infrastructure_plan_prod
          scope: list-api-cdk
          stack-output-path: infrastructure/list-api/cdktf.out/stacks/list-api
          resource-class: pocket/default-prod
          workspace: Prod
          dev: false
          apply: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: list_api
          name: list-api_infrastructure_apply_dev
          scope: list-api-cdk
          stack-output-path: infrastructure/list-api/cdktf.out/stacks/list-api
          resource-class: pocket/default-dev
          workspace: Dev
          apply: true
          dev: true

      # Build & Deploy the Dev Docker Image
      - build_image:
          <<: *only_dev
          context: pocket
          for: list_api
          name: list-api_build_docker_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: listapi-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=list-api --build-arg APP_PATH=servers/list-api --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=list-api --build-arg PORT=4005
          requires:
            - list-api_infrastructure_apply_dev

      - code_deploy_ecs:
          <<: *only_dev
          context: pocket
          for: list_api
          name: list-api_code_deploy_ecs_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: ListAPI-Dev-ECS
          codedeploy-group-name: ListAPI-Dev-ECS
          requires:
            - list-api_build_docker_dev

      # Notify sentry of dev deployment
      - sentry_release_notification:
          <<: *only_dev
          name: list-api_sentry-release-notification-dev
          context: pocket
          for: list_api
          sentry_project_name: list-api
          sentry_env: development
          sentry_org: pocket
          requires:
            - list-api_code_deploy_ecs_dev
     
      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_dev
          name: list-api_deploy-params-dev
          aws_access_key_id: Dev_AWS_ACCESS_KEY
          aws_secret_access_key: Dev_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Dev
          service_name: ListAPI
          requires:
            - list-api_code_deploy_ecs_dev


      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: list_api
          name: list-api_infrastructure_apply_prod
          scope: list-api-cdk
          stack-output-path: infrastructure/list-api/cdktf.out/stacks/list-api
          resource-class: pocket/default-prod
          workspace: Prod
          apply: true
          dev: false

      # Build & Deploy the Prod Docker Image
      - build_image:
          <<: *only_main
          context: pocket
          for: list_api
          name: list-api_build_docker_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          repo-name: listapi-prod-app
          ecr-url: 996905175585.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=list-api --build-arg APP_PATH=servers/list-api --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=list-api --build-arg PORT=4005
          requires:
            - list-api_infrastructure_apply_prod

      - code_deploy_ecs:
          <<: *only_main
          context: pocket
          for: list_api
          name: list-api_code_deploy_ecs_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: ListAPI-Prod-ECS
          codedeploy-group-name: ListAPI-Prod-ECS
          requires:
            - list-api_build_docker_prod

      # Notify sentry of main deployment
      - sentry_release_notification:
          <<: *only_main
          name: list-api_sentry-release-notification-prod
          context: pocket
          for: list_api
          sentry_project_name: list-api
          sentry_env: production
          sentry_org: pocket
          requires:
            - list-api_code_deploy_ecs_prod

      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_main
          name: list-api_deploy-params-prod
          aws_access_key_id: Prod_AWS_ACCESS_KEY
          aws_secret_access_key: Prod_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Prod
          service_name: ListAPI
          requires:
            - list-api_code_deploy_ecs_prod
