
workflows:
  parser-graphql-wrapper:
    jobs:

      ######
      # Every PR Jobs
      ######
      - apollo:
          name: parser-graphql-wrapper_apollo
          fed_graph_name: pocket-client-api
          graph_name: parser
          schema_file_path: servers/parser-graphql-wrapper/schema.graphql
          prod_graph_url: https://parser-graphql-wrapper.readitlater.com
          dev_graph_url: https://parser-graphql-wrapper.getpocket.dev

      - apollo:
          name: parser-graphql-wrapper_apollo_admin
          fed_graph_name: pocket-admin-api
          schema_file_path: servers/parser-graphql-wrapper/schema.graphql
          graph_name: parser
          prod_graph_url: https://parser-graphql-wrapper.readitlater.com
          dev_graph_url: https://parser-graphql-wrapper.getpocket.dev
          apollo_key_env: APOLLO_ADMIN_KEY

      - test_integrations:
          <<: *not_dev_main
          for: parser_graphql_wrapper
          context: pocket
          name: parser-graphql-wrapper_test_integrations
          scope: parser-graphql-wrapper

      # Try building the ECS docker image on each branch
      - build_image:
          <<: *not_dev_main
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_build_docker
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: parsergraphqlwrapper-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: false
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=parser-graphql-wrapper --build-arg APP_PATH=servers/parser-graphql-wrapper --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=parser-graphql-wrapper --build-arg PORT=4001 
     
      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_infrastructure_plan_prod
          scope: parser-graphql-wrapper-cdk
          stack-output-path: infrastructure/parser-graphql-wrapper/cdktf.out/stacks/parser-graphql-wrapper
          resource-class: pocket/default-prod
          dev: false
          apply: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_infrastructure_apply_dev
          scope: parser-graphql-wrapper-cdk
          stack-output-path: infrastructure/parser-graphql-wrapper/cdktf.out/stacks/parser-graphql-wrapper
          resource-class: pocket/default-dev
          apply: true
          dev: true

      # Build & Deploy the Dev Docker Image
      - build_image:
          <<: *only_dev
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_build_docker_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          repo-name: parsergraphqlwrapper-dev-app
          ecr-url: 410318598490.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=parser-graphql-wrapper --build-arg APP_PATH=servers/parser-graphql-wrapper --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=parser-graphql-wrapper --build-arg PORT=4001
          requires:
            - parser-graphql-wrapper_infrastructure_apply_dev

      - code_deploy_ecs:
          <<: *only_dev
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_code_deploy_ecs_dev
          resource-class: pocket/default-dev
          requires:
            - parser-graphql-wrapper_build_docker_dev

      # Notify sentry of dev deployment
      - sentry_release_notification:
          <<: *only_dev
          name: parser-graphql-wrapper_sentry-release-notification-dev
          context: pocket
          for: parser_graphql_wrapper
          sentry_project_name: parser-graphql-wrapper
          sentry_env: development
          sentry_org: pocket
          requires:
            - parser-graphql-wrapper_code_deploy_ecs_dev

      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_infrastructure_apply_prod
          scope: parser-graphql-wrapper-cdk
          stack-output-path: infrastructure/parser-graphql-wrapper/cdktf.out/stacks/parser-graphql-wrapper
          resource-class: pocket/default-prod
          apply: true
          dev: false

      # Build & Deploy the Prod Docker Image
      - build_image:
          <<: *only_main
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_build_docker_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          repo-name: parsergraphqlwrapper-prod-app
          ecr-url: 996905175585.dkr.ecr.us-east-1.amazonaws.com
          push: true
          extra-build-args: --build-arg GIT_SHA=${CIRCLE_SHA1} --build-arg SCOPE=parser-graphql-wrapper --build-arg APP_PATH=servers/parser-graphql-wrapper --build-arg SENTRY_AUTH_TOKEN=${SENTRY_BEARER} --build-arg SENTRY_ORG=pocket --build-arg SENTRY_PROJECT=parser-graphql-wrapper --build-arg PORT=4001
          requires:
            - parser-graphql-wrapper_infrastructure_apply_prod

      - code_deploy_ecs:
          <<: *only_main
          context: pocket
          for: parser_graphql_wrapper
          name: parser-graphql-wrapper_code_deploy_ecs_prod
          resource-class: pocket/default-prod
          requires:
            - parser-graphql-wrapper_build_docker_prod

      # Notify sentry of main deployment
      - sentry_release_notification:
          <<: *only_main
          name: parser-graphql-wrapper_sentry-release-notification-prod
          context: pocket
          for: parser_graphql_wrapper
          sentry_project_name: parser-graphql-wrapper
          sentry_env: production
          sentry_org: pocket
          requires:
            - parser-graphql-wrapper_code_deploy_ecs_prod
