jobs:
  lint:
    docker:
      - image: *node_image
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Lint
          command: |
            pnpm run lint

  mismatched_versions:
    docker:
      - image: *node_image
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Check for Mismatch
          command: |
            pnpm list-mismatches

  test:
    docker:
      - image: *node_image
    resource_class: xlarge
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Test
          command: |
            pnpm run test --concurrency=2

workflows:
  repo:
    jobs:
      - lint:
          <<: *not_dev_main
          context: pocket
      - test:
          <<: *not_dev_main
          context: pocket
      - mismatched_versions:
          <<: *not_dev_main
          context: pocket