jobs:
  lint:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Lint
          command: |
            pnpm run lint
  test:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Test
          command: |
            pnpm run test

workflows:
  repo:
    jobs:
      - lint:
          <<: *not_dev_main
          context: pocket
      - test:
          <<: *not_dev_main
          context: pocket