jobs:
  lint:
    docker:
      - image: *node_image
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Lint
          # Need to build first, so the linter picks up all needed imports
          command: |
            pnpm run build
            pnpm run lint
  test:
    docker:
      - image: *node_image
    steps:
      - checkout
      - install_pnpm
      - run:
          name: Test
          command: |
            pnpm run test

workflows:
  repo:
    jobs:
      - lint:
          <<: *not_dev_main
          context: pocket
      - test:
          <<: *not_dev_main
          context: pocket