
workflows:
  sendgrid-data:
    jobs:

      ######
      # Every PR Jobs
      ######
      - build_lambda:
          <<: *not_dev_main
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_build_lambda
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: sendgrid-data
          sentry_project_name: sendgrid-data
          sentry_env: development
          sentry_org: pocket

      - infrastructure:
          <<: *not_dev_main
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_infrastructure_plan_prod
          scope: sendgrid-data-cdk
          stack-output-path: infrastructure/sendgrid-data/cdktf.out/stacks/sendgrid-data
          resource-class: pocket/default-prod
          dev: false
          apply: false
          save_app_spec: false

      ######
      # Dev Branch Deployment (Dev Environment)
      ######

      - infrastructure:
          <<: *only_dev
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_infrastructure_apply_dev
          scope: sendgrid-data-cdk
          stack-output-path: infrastructure/sendgrid-data/cdktf.out/stacks/sendgrid-data
          resource-class: pocket/default-dev
          apply: true
          dev: true
          save_app_spec: false

      - build_lambda:
          <<: *only_dev
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_build_lambda_dev
          aws-access-key-id: Dev_AWS_ACCESS_KEY
          aws-secret-access-key: Dev_AWS_SECRET_ACCESS_KEY
          aws-region: Dev_AWS_DEFAULT_REGION
          scope: sendgrid-data
          sentry_project_name: sendgrid-data
          sentry_env: development
          sentry_org: pocket
          s3-bucket: pocket-sendgriddata-dev-apigateway
          requires:
            - sendgrid-data_infrastructure_apply_dev

      - code_deploy_lambda:
          <<: *only_dev
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_code_deploy_lambda_dev
          resource-class: pocket/default-dev
          codedeploy-app-name: SendGridData-Dev-ApiGateway-Lambda
          codedeploy-group-name: SendGridData-Dev-ApiGateway-Lambda
          function-name: SendGridData-Dev-ApiGateway-Function
          s3-bucket: pocket-sendgriddata-dev-apigateway
          requires:
            - sendgrid-data_build_lambda_dev


      # Notify sentry of dev deployment
      - sentry_release_notification:
          <<: *only_dev
          name: sendgrid-data_sentry-release-notification-dev
          context: pocket
          for: sendgrid_data
          sentry_project_name: sendgrid-data
          sentry_env: development
          sentry_org: pocket
          requires:
            - sendgrid-data_code_deploy_lambda_dev

      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_dev
          name: sendgrid-data_deploy-params-dev
          aws_access_key_id: Dev_AWS_ACCESS_KEY
          aws_secret_access_key: Dev_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Dev
          service_name: SendGridData
          requires:
            - sendgrid-data_code_deploy_lambda_dev

      ######
      # Main Branch Deployment (Prod Environment)
      ######
      - infrastructure:
          <<: *only_main
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_infrastructure_apply_prod
          scope: sendgrid-data-cdk
          stack-output-path: infrastructure/sendgrid-data/cdktf.out/stacks/sendgrid-data
          resource-class: pocket/default-prod
          apply: true
          dev: false
          save_app_spec: false
      - build_lambda:
          <<: *only_main
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_build_lambda_prod
          aws-access-key-id: Prod_AWS_ACCESS_KEY
          aws-secret-access-key: Prod_AWS_SECRET_ACCESS_KEY
          aws-region: Prod_AWS_DEFAULT_REGION
          scope: sendgrid-data
          sentry_project_name: sendgrid-data
          sentry_env: prodelopment
          sentry_org: pocket
          s3-bucket: pocket-sendgriddata-prod-apigateway
          requires:
            - sendgrid-data_infrastructure_apply_prod

      - code_deploy_lambda:
          <<: *only_main
          context: pocket
          for: sendgrid_data
          name: sendgrid-data_code_deploy_lambda_prod
          resource-class: pocket/default-prod
          codedeploy-app-name: SendGridData-Prod-ApiGateway-Lambda
          codedeploy-group-name: SendGridData-Prod-ApiGateway-Lambda
          function-name: SendGridData-Prod-ApiGateway-Function
          s3-bucket: pocket-sendgriddata-prod-apigateway
          requires:
            - sendgrid-data_build_lambda_prod


      # Notify sentry of prod deployment
      - sentry_release_notification:
          <<: *only_main
          name: sendgrid-data_sentry-release-notification-prod
          context: pocket
          for: sendgrid_data
          sentry_project_name: sendgrid-data
          sentry_env: prodelopment
          sentry_org: pocket
          requires:
            - sendgrid-data_code_deploy_lambda_prod

      # Setup params we may use in Lambdas
      - setup_deploy_params:
          <<: *only_main
          name: sendgrid-data_deploy-params-prod
          aws_access_key_id: Prod_AWS_ACCESS_KEY
          aws_secret_access_key: Prod_AWS_SECRET_ACCESS_KEY
          context: pocket
          env: Prod
          service_name: SendGridData
          requires:
            - sendgrid-data_code_deploy_lambda_prod