federation_version: =2.4.7
subgraphs:
  products:
    routing_url: http://localhost:4001
    schema:
      subgraph_url: http://localhost:4001
  users:
    routing_url: http://localhost:4002
    schema:
      subgraph_url: http://localhost:4002
