/***
 * User registration schema class generated by the schema registry code bindings
 */
export class UserRegistrationEvent {
  'email': string;
  'encodedUserId': string | undefined;
  'userId': string;
  'locale': string;

  private static discriminator: string | undefined = undefined;
  private static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'email',
      baseName: 'email',
      type: 'string',
    },
    {
      name: 'encodedUserId',
      baseName: 'encodedUserId',
      type: 'string',
    },
    {
      name: 'userId',
      baseName: 'userId',
      type: 'string',
    },
    {
      name: 'locale',
      baseName: 'locale',
      type: 'string',
    },
  ];

  public static getAttributeTypeMap() {
    return UserRegistrationEvent.attributeTypeMap;
  }
}
