sandbox:
  enabled: false
supergraph:
  introspection: true
  listen: 0.0.0.0:${env.PORT:-4001}
  query_planning:
    cache:
      redis:
        urls: ['${env.REDIS_PROTOCOL:-rediss-cluster}://${env.REDIS_ENDPOINT}']
        ttl: 48h # optional, by default no expiration
include_subgraph_errors:
  all: true # Propagate errors from all subgraphs
health_check:
  listen: 0.0.0.0:${env.PORT}
  enabled: true
  path: /.well-known/apollo/server-health
limits:
  parser_max_tokens: 15000 # This is the default value.
  parser_max_recursion: 4096 # This is the default value.
  max_depth: 100 # Must be 15 or larger to support standard introspection query
  max_height: 225
  max_aliases: 30
  max_root_fields: 20
authentication:
  router:
    jwt:
      jwks:
        - url: https://getpocket.com/.well-known/jwk
authorization:
  require_authentication: false
rhai:
  scripts: './rhai'
  main: 'main.rhai'
headers:
  all:
    request:
      # Note: Additional JWT headers and headers which need special processing
      # are handled in Rhai scripts
      - propagate:
          named: 'web-request-langugage'
          rename: 'gatewayLanguage'
      - propagate:
          named: 'web-request-ip-address'
          rename: 'gatewayIpAddress'
      - propagate:
          named: 'web-request-snowplow-domain-user-id'
          rename: 'gatewaySnowplowDomainUserId'
      - propagate:
          named: 'web-request-user-agent'
          rename: 'gatwayUserAgent'
      - propagate:
          named: 'transfersub'
      - propagate:
          named: 'web-request-snowplow-session-user-id'
          rename: 'gatewaySnowplowDomainSessionId'
telemetry:
  instrumentation:
    instruments:
      router:
        http.server.active_requests: true # (default false)
        http.server.request.body.size: true # (default false)
        http.server.request.duration: true # (default false)
      subgraph:
        http.client.request.body.size: true # (default false)
        http.client.request.duration: true # (default false)
        http.client.response.body.size: true # (default false)

  apollo:
    send_variable_values:
      only:
        - filters # getCollections
        - page # getCollections
        - perPage # getCollections
        - slug # collectionBySlug
  exporters:
    metrics:
      common:
        resource:
          'environment.name': '${env.APP_ENVIRONMENT}'
        service_name: 'client-api'
      otlp:
        enabled: true
        endpoint: 'http://${env.OTLP_COLLECTOR_HOST:-localhost}:4317'
        protocol: grpc
        batch_processor:
          scheduled_delay: 100ms
          max_concurrent_exports: 1000
          max_export_batch_size: 10000
          max_export_timeout: 100s
          max_queue_size: 10000
    tracing:
      common:
        resource:
          'environment.name': '${env.APP_ENVIRONMENT:-local}'
        service_name: 'client-api'
        sampler: always_on #0.1 # (default) all requests are sampled (always_on|always_off|<0.0-1.0>)
        parent_based_sampler: true
      propagation:
        aws_xray: true

      experimental_response_trace_id:
        enabled: true
        header_name: 'pocket-trace-id'
      otlp:
        enabled: true
        endpoint: 'http://${env.OTLP_COLLECTOR_HOST:-localhost}:4317'
        protocol: grpc
        batch_processor:
          scheduled_delay: 100ms
          max_concurrent_exports: 1000
          max_export_batch_size: 10000
          max_export_timeout: 100s
          max_queue_size: 10000
apq:
  router:
    cache:
      redis:
        urls: ['${env.REDIS_PROTOCOL:-rediss-cluster}://${env.REDIS_ENDPOINT}']
        ttl: 24h # optional, by default no expiration
