/* eslint-disable */
/***
 * FogotPasswordResetEvent schema class generated by the schema registry code bindings
 */
import { PasswordResetInfo } from './forgotPasswordReset/PasswordResetInfo';
import { User } from './forgotPasswordReset/User';

export class FogotPasswordResetEvent {
  'passwordResetInfo': PasswordResetInfo;
  'user': User;

    private static discriminator: string | undefined = undefined;

    private static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "passwordResetInfo",
            "baseName": "passwordResetInfo",
            "type": "PasswordResetInfo"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User"
        }    ];

    public static getAttributeTypeMap() {
        return FogotPasswordResetEvent.attributeTypeMap;
    }
}




