# Note this is only built nightly and will take effect on the next deploy after being built.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # gRPC port for receiving traces, metrics, and logs over gRPC
exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  batch:
  resourcedetection/ecs:
      detectors: [env, ecs]
      timeout: 2s
      override: false
  attributes:
    actions:
      - key: "service.namespace"
        value: "pocket"
        action: insert
      - key: "g.co/r/generic_node/namespace"
        value: "pocket"
        action: insert
      # This is reserved in GCP and our code sets it to us-east1d which is unknown to google.
      - key: "location"
        value: "us-east1"
        action: update
        
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection/ecs, attributes, memory_limiter, batch]
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [resourcedetection/ecs, attributes, memory_limiter, batch]
      exporters: [googlecloud]
    logs:
      receivers: [otlp]
      processors: [resourcedetection/ecs, attributes, memory_limiter, batch]
      exporters: [googlecloud]