# Note this is only built nightly and will take effect on the next deploy after being built.
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317" # gRPC port for receiving traces, metrics, and logs over gRPC
exporters:
  googlecloud:
    log:
      default_log_name: opentelemetry.io/collector-exported-log
  # debug:
  #   verbosity: detailed
processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 65
    spike_limit_percentage: 20
  batch:
    # batch metrics before sending to reduce API usage
    send_batch_max_size: 200
    send_batch_size: 200
    timeout: 5s
  resourcedetection/ecs:
      detectors: [env, ecs]
      timeout: 2s
      override: false
  resource/cleanup_for_google:
    attributes:
      - key: service.namespace
        value: pocket
        action: insert
      # We must set the region to us-east1, as the google exporter uses this to know where to send data to.
      - key: cloud.region
        value: us-east1
        action: upsert
      - key: cloud.availability_zone
        value: us-east1-b
        action: upsert
      # set this to the ecs task id
      - key: host.id
        from_attribute: aws.ecs.task.id
        action: upsert

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection/ecs, resource/cleanup_for_google, memory_limiter, batch]
      exporters: [googlecloud]
    metrics:
      receivers: [otlp]
      processors: [resourcedetection/ecs, resource/cleanup_for_google, memory_limiter, batch]
      exporters: [googlecloud]
    logs:
      receivers: [otlp]
      processors: [resourcedetection/ecs, resource/cleanup_for_google, memory_limiter, batch]
      exporters: [googlecloud]