name: Account Data Deleter
on:
  pull_request:
    paths:
      - 'infrastructure/account-data-deleter/**'
      - 'packages/**'
      - 'docker-compose.yml'
      - 'servers/account-data-deleter/**'
      - 'lambdas/account-data-deleter-batch-delete/**'
      - 'lambdas/account-data-deleter-events/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/account-data-deleter.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/account-data-deleter/**'
      - 'packages/**'
      - 'servers/account-data-deleter/**'
      - 'lambdas/account-data-deleter-batch-delete/**'
      - 'lambdas/account-data-deleter-events/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/account-data-deleter.yml'
      - '.github/workflows/reuse-*.yml'
jobs:
  test-integrations:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reuse-test-integrations.yml
    with:
      scope: account-data-deleter
    secrets: inherit

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: account-data-deleter-cdk
      stack-output-path: infrastructure/account-data-deleter/cdktf.out/stacks/account-data-deleter
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: account-data-deleter
      app-path: servers/account-data-deleter
      app-port: 4015
      sentry-project: account-data-deleter
      docker-repo-name-pattern: accountdatadeleter-{0}-app
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit

  events-lambda:
    uses: ./.github/workflows/reuse-build-and-push-lambda.yml
    needs: [infrastructure]
    with:
      scope: account-data-deleter-events
      sentry-project: account-data-deleter
      s3-bucket-pattern: pocket-accountdatadeleter-{0}-sqs-event-consumer
      codedeploy-app-name-pattern: AccountDataDeleter-{0}-Sqs-Event-Consumer-Lambda
      codedeploy-group-name-pattern: AccountDataDeleter-{0}-Sqs-Event-Consumer-Lambda
      function-name-pattern: AccountDataDeleter-{0}-Sqs-Event-Consumer-Function
    secrets: inherit

  batch-delete-lambda:
    uses: ./.github/workflows/reuse-build-and-push-lambda.yml
    needs: [infrastructure]
    with:
      scope: account-data-deleter-batch-delete
      sentry-project: account-data-deleter
      s3-bucket-pattern: pocket-accountdatadeleter-{0}-batchdeletelambda
      codedeploy-app-name-pattern: AccountDataDeleter-{0}-BatchDeleteLambda-Lambda
      codedeploy-group-name-pattern: AccountDataDeleter-{0}-BatchDeleteLambda-Lambda
      function-name-pattern: AccountDataDeleter-{0}-BatchDeleteLambda-Function
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [api, events-lambda, batch-delete-lambda]
    with:
      sentry-project: account-data-deleter
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit
