name: Braze
on:
  pull_request:
    paths:
      - 'infrastructure/braze/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/braze.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev

jobs:

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: braze-cdk
      stack-output-path: infrastructure/braze/cdktf.out/stacks/braze
    secrets: inherit
