name: Braze Content Proxy
on:
  pull_request:
    paths:
      - 'infrastructure/braze-content-proxy/**'
      - 'packages/**'
      - 'docker-compose.yml'
      - 'servers/braze-content-proxy/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/braze-content-proxy.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/braze-content-proxy/**'
      - 'packages/**'
      - 'servers/braze-content-proxy/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/braze-content-proxy.yml'
      - '.github/workflows/reuse-*.yml'    
jobs:
  test-integrations:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reuse-test-integrations.yml
    with:
      scope: '@server/braze-content-proxy'
    secrets: inherit

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: '@infrastructure/braze-content-proxy'
      stack-output-path: infrastructure/braze-content-proxy/cdktf.out/stacks/braze-content-proxy
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: '@server/braze-content-proxy'
      app-path: servers/braze-content-proxy
      app-port: 4500
      sentry-project: braze-content-proxy
      docker-repo-name-pattern: brazecontentproxy-{0}-app
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [api]
    with:
      sentry-project: braze-content-proxy
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit