name: Client API
on:
  pull_request:
    paths:
      - 'infrastructure/client-api/**'
      - 'packages/**'
      - 'docker-compose.yml'
      - 'servers/client-api/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/client-api.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/client-api/**'
      - 'packages/**'
      - 'servers/client-api/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/client-api.yml'
      - '.github/workflows/reuse-*.yml'
jobs:

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: '@infrastructure/client-api'
      stack-output-path: infrastructure/client-api/cdktf.out/stacks/client-api
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: '@server/client-api'
      docker-repo-name-pattern: clientapi-{0}-app
      context: servers/client-api
      app-path: servers/client-api
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit