name: Docker Images
on:
    pull_request:
    push:
        branches:
            - main
    schedule: # Rebuild images nightly
      - cron: '0 0 * * *'

jobs:
  otel:
      runs-on: ubuntu-latest
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build Base
          uses: docker/build-push-action@v6
          with:
            push: ${{ github.ref == 'refs/heads/main' && true || false}}
            platforms: linux/amd64,linux/arm64
            tags: pocket/opentelemetry-collector-contrib
            context: "{{defaultContext}}:images/otel"