name: Feature Flags
on:
  pull_request:
    paths:
      - 'infrastructure/feature-flags/**'
      - 'packages/**'
      - 'servers/feature-flags/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/feature-flags.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/feature-flags/**'
      - 'packages/**'
      - 'servers/feature-flags/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/feature-flags.yml'
      - '.github/workflows/reuse-*.yml'
jobs:
  apollo:
    uses: ./.github/workflows/reuse-apollo-federation.yml
    with:
      federated-graph-name: pocket-client-api
      graph-name: featureflags
      schema-file-path: servers/feature-flags/schema.graphql
      prod-graph-url: https://featureflags.readitlater.com/graphql
      dev-graph-url: https://featureflags.getpocket.dev/graphql
    secrets:
      apollo-key: ${{ secrets.APOLLO_CLIENT_API_KEY }}

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: feature-flags-cdk
      stack-output-path: infrastructure/feature-flags/cdktf.out/stacks/feature-flags
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: feature-flags
      app-path: servers/feature-flags
      app-port: 4242
      sentry-project: feature-flags
      docker-repo-name-pattern: featureflags-{0}-app
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [api]
    with:
      sentry-project: feature-flags
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit