name: Instant Sync Events
on:
  pull_request:
    paths:
      - 'infrastructure/instant-sync-events/**'
      - 'packages/**'
      - 'lambdas/instant-sync-events/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/instant-sync-events.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/instant-sync-events/**'
      - 'packages/**'
      - 'lambdas/instant-sync-events/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/instant-sync-events.yml'
      - '.github/workflows/reuse-*.yml'
jobs:

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: instant-sync-events-cdk
      stack-output-path: infrastructure/instant-sync-events/cdktf.out/stacks/instant-sync-events
    secrets: inherit

  lambda:
    uses: ./.github/workflows/reuse-build-and-push-lambda.yml
    needs: [infrastructure]
    with:
      scope: instant-sync-events
      sentry-project: instant-sync-events
      s3-bucket-pattern: pocket-instantsyncevents-{0}-eventtracker
      codedeploy-app-name-pattern: InstantSyncEvents-{0}-EventTracker-Lambda
      codedeploy-group-name-pattern: InstantSyncEvents-{0}-EventTracker-Lambda
      function-name-pattern: InstantSyncEvents-{0}-EventTracker-Function
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [lambda]
    with:
      sentry-project: annotations-api
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit
