name: List API
on:
  pull_request:
    paths:
      - 'infrastructure/list-api/**'
      - 'packages/**'
      - 'servers/list-api/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/list_api.yml'

jobs:
  test-integrations:
    uses: ./.github/workflows/test_integrations.yml
    with:
      scope: 'list-api'
    # Ensure the re-usable workflow is allowed to access the secrets
    secrets: inherit