name: Notes API
on:
  pull_request:
    paths:
      - 'infrastructure/notes-api/**'
      - 'packages/**'
      - 'docker-compose.yml'
      - 'servers/notes-api/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/notes-api.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/notes-api/**'
      - 'packages/**'
      - 'servers/notes-api/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/notes-api.yml'
      - '.github/workflows/reuse-*.yml'
jobs:
  test-integrations:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reuse-test-integrations.yml
    with:
      scope: '@server/notes-api'
    secrets: inherit

  apollo:
    uses: ./.github/workflows/reuse-apollo-federation.yml
    with:
      federated-graph-name: pocket-client-api
      graph-name: notes-api
      schema-file-path: servers/notes-api/dist/schema-generated.graphql
      prod-graph-url: https://notes.readitlater.com
      dev-graph-url: https://notes.getpocket.dev
      scope: '@server/notes-api'
    secrets:
      apollo-key: ${{ secrets.APOLLO_CLIENT_API_KEY }}

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: '@infrastructure/notes-api'
      stack-output-path: infrastructure/notes-api/cdktf.out/stacks/notes-api
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: '@server/notes-api'
      app-path: servers/notes-api
      app-port: 4029
      sentry-project: notes-api
      docker-repo-name-pattern: notesapi-{0}-app
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [api]
    with:
      sentry-project: notes-api
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit
