name: Parser GraphQL Wrapper
on:
  pull_request:
    paths:
      - 'infrastructure/parser-graphql-wrapper/**'
      - 'packages/**'
      - 'docker-compose.yml'
      - 'servers/parser-graphql-wrapper/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/parser-graphql-wrapper.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/parser-graphql-wrapper/**'
      - 'packages/**'
      - 'servers/parser-graphql-wrapper/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/parser-graphql-wrapper.yml'
      - '.github/workflows/reuse-*.yml'    
jobs:
  test-integrations:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reuse-test-integrations.yml
    with:
      scope: parser-graphql-wrapper
    secrets: inherit

  apollo:
    uses: ./.github/workflows/reuse-apollo-federation.yml
    with:
      federated-graph-name: pocket-client-api
      graph-name: parser
      schema-file-path: servers/parser-graphql-wrapper/schema.graphql
      prod-graph-url: https://parser-graphql-wrapper.readitlater.com
      dev-graph-url: https://parser-graphql-wrapper.getpocket.dev
    secrets:
      apollo-key: ${{ secrets.APOLLO_CLIENT_API_KEY }}

  apollo-admin:
    uses: ./.github/workflows/reuse-apollo-federation.yml
    with:
      federated-graph-name: pocket-admin-api
      graph-name: parser
      schema-file-path: servers/parser-graphql-wrapper/schema-admin.graphql
      prod-graph-url: https://parser-graphql-wrapper.readitlater.com
      dev-graph-url: https://parser-graphql-wrapper.getpocket.dev
    secrets:
      apollo-key: ${{ secrets.APOLLO_ADMIN_API_KEY }}

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: parser-graphql-wrapper-cdk
      stack-output-path: infrastructure/parser-graphql-wrapper/cdktf.out/stacks/parser-graphql-wrapper
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: parser-graphql-wrapper
      app-path: servers/parser-graphql-wrapper
      app-port: 4001
      sentry-project: parser-graphql-wrapper
      docker-repo-name-pattern: parsergraphqlwrapper-{0}-app
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [api]
    with:
      sentry-project: parser-graphql-wrapper
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit