name: Pocket Event Bridge
on:
  pull_request:
    paths:
      - 'infrastructure/pocket-event-bridge/**'
      - 'packages/**'
      - 'docker-compose.yml'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/pocket-event-bridge.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/pocket-event-bridge/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/pocket-event-bridge.yml'
      - '.github/workflows/reuse-*.yml'    
jobs:

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: '@infrastructure/pocket-event-bridge'
      stack-output-path: infrastructure/pocket-event-bridge/cdktf.out/stacks/pocket-event-bridge
    secrets: inherit