name: Pull Request
on:
  - pull_request

jobs:
  check-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm & node
        uses: ./.github/actions/install-pnpm-and-node
      
      - name: Check for mismatched dependencies
        run: pnpm run list-mismatches

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Install pnpm & node
        uses: ./.github/actions/install-pnpm-and-node

      - name: Check for mismatched dependencies
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm & node
        uses: ./.github/actions/install-pnpm-and-node
      
      - name: Unit Tests
        # Following uses a 2 concurrency because terraform modules seems to fail with an OOM error on CI if we do more.
        run: pnpm run test --concurrency=2 