name: Node.js Package
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  merge_group:

jobs:
  ##
  # Runs semantic release in a regular
  ##
  release:
    name: Semantic Release
    timeout-minutes: 15
    runs-on: ubuntu-latest

    # https://github.com/semantic-release/npm
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Install pnpm & node
        uses: pocket/pocket-monorepo/.github/actions/install-pnpm-and-node@main

      - name: Semantic Release
        run: pnpm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          # Need to update sendgrid to enable this
          #        NPM_CONFIG_PROVENANCE: true
