name: Push Server
on:
  pull_request:
    paths:
      - 'infrastructure/push-server/**'
      - 'packages/**'
      - 'servers/push-server/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/push-server.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    
jobs:
  test-integrations:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reuse-test-integrations.yml
    with:
      scope: push-server
    secrets: inherit

  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: push-server-cdk
      stack-output-path: infrastructure/push-server/cdktf.out/stacks/push-server
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: push-server
      app-path: servers/push-server
      sentry-project: push-server
      docker-repo-name-pattern: push-{0}-app
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [api]
    with:
      sentry-project: push-server
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit