name: Shareable Lists API
on:
  pull_request:
    paths:
      - 'infrastructure/shareable-lists-api/**'
      - 'packages/**'
      - 'servers/shareable-lists-api/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/shareable-lists-api.yml'
      - '.github/workflows/reuse-*.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'infrastructure/shareable-lists-api/**'
      - 'packages/**'
      - 'servers/shareable-lists-api/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
      - '.github/actions/**'
      - '.github/workflows/shareable-lists-api.yml'
      - '.github/workflows/reuse-*.yml'    
jobs:
  test-integrations:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/reuse-test-integrations.yml
    with:
      scope: shareable-lists-api
    secrets: inherit

  apollo:
    uses: ./.github/workflows/reuse-apollo-federation.yml
    with:
      federated-graph-name: pocket-client-api
      graph-name: shareable-lists-api
      schema-file-path: servers/shareable-lists-api/schema-client-api.graphql
      prod-graph-url: https://shareablelistsapi.readitlater.com
      dev-graph-url: https://shareablelistsapi.getpocket.dev
      scope: shareable-lists-api
    secrets:
      apollo-key: ${{ secrets.APOLLO_CLIENT_API_KEY }}

  apollo-admin:
    uses: ./.github/workflows/reuse-apollo-federation.yml
    with:
      federated-graph-name: pocket-admin-api
      graph-name: shareable-lists-api
      schema-file-path: servers/shareable-lists-api/schema-admin-api.graphql
      prod-graph-url: https://shareablelistsapi.readitlater.com/admin
      dev-graph-url: https://shareablelistsapi.getpocket.dev/admin
      scope: shareable-lists-api
    secrets:
      apollo-key: ${{ secrets.APOLLO_ADMIN_API_KEY }}


  infrastructure:
    uses: ./.github/workflows/reuse-infrastructure.yml
    with:
      scope: shareable-lists-api-cdk
      stack-output-path: infrastructure/shareable-lists-api/cdktf.out/stacks/shareable-lists-api
    secrets: inherit

  api:
    uses: ./.github/workflows/reuse-build-and-push-image.yml
    needs: [infrastructure]
    with:
      scope: shareable-lists-api
      app-path: servers/shareable-lists-api
      app-port: 4029
      sentry-project: shareable-lists-api
      docker-repo-name-pattern: shareablelistsapi-{0}-app
      terraform-output: ${{needs.infrastructure.outputs.terraform-output}}
    secrets: inherit

  events-lambda:
    uses: ./.github/workflows/reuse-build-and-push-lambda.yml
    needs: [infrastructure]
    with:
      scope: shareable-lists-api-events-lambda
      sentry-project: shareable-lists-api
      s3-bucket-pattern: pocket-shareablelistsapi-{0}-sqs-event-consumer
      codedeploy-app-name-pattern: ShareableListsApi-{0}-Sqs-Event-Consumer-Lambda
      codedeploy-group-name-pattern: ShareableListsApi-{0}-Sqs-Event-Consumer-Lambda
      function-name-pattern: ShareableListsApi-{0}-Sqs-Event-Consumer-Function
    secrets: inherit

  sentry:
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reuse-sentry-release.yml
    needs: [api, events-lambda]
    with:
      sentry-project: shareable-lists-api
      sentry-environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    secrets: inherit