name: 'Re-usable Test Integrations'
on:
  workflow_call:
    inputs:
      scope:
        description: 'Turbo Repo scope to run tests for'
        required: true
        type: string

jobs:
  test-integrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Kick off starting docker compose first, since it can take a bit
    - name: Start Docker Compose services
      run: docker compose up -d
    
    # While we wait for docker compose to be healthy we install node and needed packages.
    - name: Install pnpm & node
      uses: ./.github/actions/install-pnpm-and-node
      with:
        scope: ${{ inputs['scope'] }}
    
    # Step 4: Wait for the services to be healthy
    - name: Wait for services to be healthy
      run: docker compose up --wait
    
    # TODO: In the future, we should figure out how to pass a scope to the Localstack startup routine
    # in circleci, we had to do it all manually so we passed it in then.
    - name: Wait for Localstack to be ready
      run: curl -s localhost:4566/_localstack/init/ready | jq .completed

    - name: Run service integration tests
      run: pnpm run test-integrations --filter=${{ inputs['scope'] }}