name: User API
on:
  # Only run the tests for this service when any of the following file paths change
  pull_request:
    paths:
      - 'infrastructure/user-api/**'
      - 'packages/**'
      - 'servers/user-api/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/user_api.yml'

jobs:
  # Let's test the service against some real life and mocked docker services.
  test-integrations:
    # Use our re-usable test integrations workflow which will use our docker compose file
    uses: ./.github/workflows/test-integrations.yml
    with:
      # Only run the tests for our service
      scope: 'user-api'
    # Ensure the re-usable workflow is allowed to access the secrets
    secrets: inherit