name: User API
on:
  pull_request:
    paths:
      - 'infrastructure/user-api/**'
      - 'packages/**'
      - 'servers/user-api/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/user_api.yml'

jobs:
  test-integrations:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Kick off starting docker compose first, since it can take a bit
    - name: Start Docker Compose services
      run: docker-compose up -d
    
    # While we wait for docker compose to be healthy we install node and needed packages.
    - name: Install pnpm & node
      uses: ./.github/actions/install-pnpm-and-node
      with:
        scope: user-api
    
    # Step 4: Wait for the services to be healthy
    - name: Wait for services to be healthy
      run: |
        docker-compose wait
    - name: Run service integration tests
      run: pnpm run test-integrations --filter=user-api...