name: User API
on:
  # Only run the tests for this service when any of the following file paths change
  pull_request:
    paths:
      - 'infrastructure/user-api/**'
      - 'packages/**'
      - 'servers/user-api/**'
      - 'pnpm-lock.yaml'
      - '.github/actions/**'
      - '.github/workflows/user_api.yml'
  push:
    branches:
      - main
      - dev

jobs:
  # Let's test the service against some real life and mocked docker services.
  test-integrations:
    # Only run this job on a pull request event
    if: github.event_name == 'pull_request'
    # Use our re-usable test integrations workflow which will use our docker compose file
    uses: ./.github/workflows/test-integrations.yml
    with:
      # Only run the tests for our service
      scope: 'user-api'
    # Ensure the re-usable workflow is allowed to access the secrets
    secrets: inherit

  # Let's test the service against some real life and mocked docker services.
  build-and-push-image:
    uses: ./.github/workflows/build-and-push-image.yml
    with:
      scope: user-api
      app-path: servers/user-api
      app-port: 4006
      sentry-project: user-api
      docker-repo-name-short-hand: userapi
    # Ensure the re-usable workflow is allowed to access the secrets
    secrets: inherit